export const Assets = {
  icons: {
    search: require("../assets/icons/search.png"),
    home: require("../assets/icons/home.png"),
    dumbbell: require("../assets/icons/dumbbell.png"),
    nutrition: require("../assets/icons/nutrition.png"),
    profile: require("../assets/icons/profile.png"),
    home1: require("../assets/icons/home1.png"),
    dumbbell1: require("../assets/icons/dumbbell1.png"),
    nutrition1: require("../assets/icons/nutrition1.png"),
    profile1: require("../assets/icons/profile1.png"),
    arrow: require("../assets/icons/arrow.png"),
    arrow1: require("../assets/icons/arrow1.png"),
    arrowBottom: require("../assets/icons/arrowBottom.png"),
    arrowTop: require("../assets/icons/arrowTop.png"),
    close: require("../assets/icons/close.png"),
  },
  images: {
    cover1: require("../assets/images/cover1.png"),
    cover2: require("../assets/images/cover2.png"),
    cover3: require("../assets/images/cover3.png"),
    cover4: require("../assets/images/cover4.png"),
    fitness: require("../assets/images/fitness.jpg"),
    avatar: require("../assets/images/avatar.png"),
  },
};
